In [1]:
import numpy as np

In [12]:
X = np.array([[1, 1], [1, 2], [2, 2], [2, 3]])
y = np.dot(X, np. array([1, 2])) + 3
print(y)

beta_gd = [10.1, 15.1, -6.5]
X_ = np.array([np.append(x, [1]) for x in X])
for t in range(5000):
    error = y - X_ @ beta_gd # beta_gd가 list 형태이므로 @ 연산은 내적을 의미
    # error = error / np.linalg.norm(error)
    grad = -np.transpose(X_) @ error
    beta_gd = beta_gd - 0.01 * grad
print(beta_gd)

[ 6  8  9 11]
[1.00000367 1.99999949 2.99999516]


In [15]:
np.array([beta_gd]).shape

(1, 3)

In [19]:
b = [1, 0, -1]

In [21]:
print('X_:\n',X_, '\nb:', b)
print('X_ @ b:', X_ @ b)
print(X_ @ [[1], [0], [-1]])

X_:
 [[1 1 1]
 [1 2 1]
 [2 2 1]
 [2 3 1]] 
b: [1, 0, -1]
X_ @ b: [0 0 1 1]
[[0]
 [0]
 [1]
 [1]]


In [22]:
X = np.array([[1, 1], [1, 2], [2, 2], [2, 3]])
y = np.dot(X, np. array([1, 2])) + 3
print(y)

beta_gd = [10.1, 15.1, -6.5]
X_ = np.array([np.append(x, [1]) for x in X])
for t in range(100):
    error = y - X_ @ beta_gd # beta_gd가 list 형태이므로 @ 연산은 내적을 의미
    # error = error / np.linalg.norm(error)
    grad = -np.transpose(X_) @ error
    beta_gd = beta_gd - 0.01 * grad
print(beta_gd)

[ 6  8  9 11]
[ 3.41314549  4.63604548 -6.69249764]
