## numpy - ndarray

In [2]:
import numpy as np
n_array = np.arange(10).reshape(2,5)
print(n_array)
print("ndim: ", n_array.ndim, 'shape:', n_array.shape)

[[0 1 2 3 4]
 [5 6 7 8 9]]
ndim:  2 shape: (2, 5)


## pytorch - tensor

In [3]:
import torch
t_array = torch.FloatTensor(n_array)
print(t_array)
print("ndim: ", t_array.ndim, 'shape:', t_array.shape)

tensor([[0., 1., 2., 3., 4.],
        [5., 6., 7., 8., 9.]])
ndim:  2 shape: torch.Size([2, 5])


## data to tensor

In [4]:
data = [[3, 5], [10, 5]]
x_data = torch.tensor(data)
x_data

tensor([[ 3,  5],
        [10,  5]])

## ndarray to tensor

In [5]:
nd_array_ex = np.array(data)
tensor_array = torch.from_numpy(nd_array_ex)
tensor_array

tensor([[ 3,  5],
        [10,  5]], dtype=torch.int32)

## numpy like operations

In [6]:
data = [[3, 5, 20], [10, 5, 50], [1, 5, 10]]
x_data = torch.tensor(data)

In [7]:
x_data[1:]

tensor([[10,  5, 50],
        [ 1,  5, 10]])

In [8]:
x_data[:2, 1:]

tensor([[ 5, 20],
        [ 5, 50]])

In [9]:
x_data.flatten()

tensor([ 3,  5, 20, 10,  5, 50,  1,  5, 10])

In [10]:
torch.ones_like(x_data)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])

In [11]:
x_data.numpy()

array([[ 3,  5, 20],
       [10,  5, 50],
       [ 1,  5, 10]], dtype=int64)

In [12]:
x_data.shape

torch.Size([3, 3])

In [13]:
x_data.dtype

torch.int64

## device(GPU)설정

In [14]:
x_data.device

device(type='cpu')

In [16]:
if torch.cuda.is_available():
    x_data_cuda = x_data.to('cuda')
x_data_cuda.device

device(type='cuda', index=0)

## 1) view

In [17]:
tensor_ex = torch.rand(size = (2, 3, 2))
tensor_ex

tensor([[[0.6387, 0.3454],
         [0.1577, 0.6862],
         [0.9079, 0.9839]],

        [[0.6805, 0.1518],
         [0.9854, 0.9330],
         [0.7001, 0.8347]]])

In [18]:
tensor_ex.view([-1, 6])

tensor([[0.6387, 0.3454, 0.1577, 0.6862, 0.9079, 0.9839],
        [0.6805, 0.1518, 0.9854, 0.9330, 0.7001, 0.8347]])

In [20]:
tensor_ex.reshape([-1, 6])

tensor([[0.6387, 0.3454, 0.1577, 0.6862, 0.9079, 0.9839],
        [0.6805, 0.1518, 0.9854, 0.9330, 0.7001, 0.8347]])

In [24]:
a = torch.zeros(3, 2)
b = a.view(2, 3)
a.fill_(1)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [25]:
a

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [26]:
b

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [29]:
a = torch.zeros(3, 2)
b = a.t().reshape(6)
a.fill_(1)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [30]:
b

tensor([0., 0., 0., 0., 0., 0.])

In [28]:
a.T, a.t()

(tensor([[1., 1., 1.],
         [1., 1., 1.]]),
 tensor([[1., 1., 1.],
         [1., 1., 1.]]))

## 2) squeeze

In [36]:
tensor_ex = torch.rand(size=(2, 1, 2))
tensor_ex

tensor([[[0.1769, 0.8536]],

        [[0.2735, 0.4758]]])

In [37]:
tensor_ex.squeeze()

tensor([[0.1769, 0.8536],
        [0.2735, 0.4758]])

## 3) unsqueeze

In [46]:
tensor_ex = torch.rand(size=(2,2))
tensor_ex

tensor([[0.7643, 0.1238],
        [0.4912, 0.0227]])

In [49]:
tensor_ex.unsqueeze(0), tensor_ex.unsqueeze(0).shape

(tensor([[[0.7643, 0.1238],
          [0.4912, 0.0227]]]),
 torch.Size([1, 2, 2]))

In [50]:
tensor_ex.unsqueeze(1), tensor_ex.unsqueeze(1).shape

(tensor([[[0.7643, 0.1238]],
 
         [[0.4912, 0.0227]]]),
 torch.Size([2, 1, 2]))

In [51]:
tensor_ex.unsqueeze(2), tensor_ex.unsqueeze(2).shape

(tensor([[[0.7643],
          [0.1238]],
 
         [[0.4912],
          [0.0227]]]),
 torch.Size([2, 2, 1]))

## tensor operations

In [54]:
n1 = np.arange(10).reshape(2,5)
n2 = np.arange(10).reshape(5,2)
t1 = torch.FloatTensor(n1)
t2 = torch.FloatTensor(n2)

t1+t1

tensor([[ 0.,  2.,  4.,  6.,  8.],
        [10., 12., 14., 16., 18.]])

In [55]:
t1-t1

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [57]:
t1+10

tensor([[10., 11., 12., 13., 14.],
        [15., 16., 17., 18., 19.]])

In [58]:
t1 + t2

RuntimeError: The size of tensor a (5) must match the size of tensor b (2) at non-singleton dimension 1

### 행렬 곱셈 연산 함수는 dot이 아닌 mm사용

In [61]:
n2 = np.arange(10).reshape(5,2)
t2 = torch.FloatTensor(n2)

t1.mm(t2)

tensor([[ 60.,  70.],
        [160., 195.]])

In [62]:
t1.dot(t2)

RuntimeError: 1D tensors expected, but got 2D and 2D tensors

In [63]:
t1.matmul(t2)

tensor([[ 60.,  70.],
        [160., 195.]])

In [64]:
t1.mm(t2)

tensor([[ 60.,  70.],
        [160., 195.]])

In [66]:
a = torch.rand(10)
b = torch.rand(10)

In [67]:
a.dot(b)

tensor(2.6064)

In [68]:
a = torch.rand(10)
b = torch.rand(10)
a.mm(b)

RuntimeError: self must be a matrix

### mm과 matmul의 차이 : broadcasting 지원 여부

In [90]:
a = torch.rand(5, 2, 3)
b = torch.rand(3)

In [91]:
a.mm(b)  

RuntimeError: self must be a matrix

In [92]:
a = torch.rand(5, 2, 3)
b = torch.rand(3)

In [93]:
a.matmul(b)

tensor([[0.5457, 1.0995],
        [0.9862, 0.7242],
        [0.5066, 1.1562],
        [0.9963, 0.3134],
        [0.5177, 0.2130]])

In [81]:
a[0].mm(torch.unsqueeze(b, 1))

tensor([0.6551, 0.8870])

In [77]:
a[1].mm(torch.unsqueeze(b, 1))

tensor([[1.2739],
        [1.2428]])

In [78]:
a[2].mm(torch.unsqueeze(b, 1))

tensor([[1.5667],
        [1.1078]])

In [79]:
a[3].mm(torch.unsqueeze(b, 1))

tensor([[1.2596],
        [1.8083]])

In [80]:
a[4].mm(torch.unsqueeze(b, 1))

tensor([[1.0884],
        [0.1771]])

## 1) softmax

In [94]:
import torch
import torch.nn.functional as F

In [95]:
tensor = torch.FloatTensor([0.5, 0.7, 0.1])
h_tensor =  F.softmax(tensor, dim=0)
h_tensor

tensor([0.3458, 0.4224, 0.2318])

## 2) onehot-encoding

In [96]:
y = torch.randint(5, (10,5))
y_label = y.argmax(dim=1)

torch.nn.functional.one_hot(y_label)

tensor([[0, 0, 0, 1, 0],
        [1, 0, 0, 0, 0],
        [0, 0, 0, 0, 1],
        [0, 0, 0, 1, 0],
        [0, 1, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0]])

## 3) cartesian_product

In [98]:
import itertools
a = [1, 2, 3]
b = [4, 5]
list(itertools.product(a, b))

[(1, 4), (1, 5), (2, 4), (2, 5), (3, 4), (3, 5)]

In [99]:
tensor_a = torch.tensor(a)
tensor_b = torch.tensor(b)
torch.cartesian_prod(tensor_a, tensor_b)

tensor([[1, 4],
        [1, 5],
        [2, 4],
        [2, 5],
        [3, 4],
        [3, 5]])

In [117]:
w = torch.tensor(2.0, requires_grad=True)
y = w**2
z= 10*y + 25
z.backward() # 실제 미분이 일어남
w.grad # w에 대해 z를 편미분한 식에 w = 2.0 대입한 값

tensor(40.)

In [118]:
a = torch.tensor([2., 3.], requires_grad=True)
b = torch.tensor([6., 4.], requires_grad=True)
Q = 3 *a**3 - b**2
external_grad = torch.tensor([1., 1.]) #external_grad: 그 이후의 gradient (넘어온 값)
Q.backward(gradient = external_grad)

In [119]:
a.grad, b.grad

(tensor([36., 81.]), tensor([-12.,  -8.]))